### PR TITLE
chore: update xcMANTA token

### PR DESCRIPTION
**Pull request by jincan39**

### CODE REVIEW

**Review by anaye1997 — APPROVED** [review]

**Comment by ADRIYAN529** [comment]
#277

**Comment by ADRIYAN529** [comment]
Adriyan

**Comment by ADRIYAN529** [comment]
No one assigned

**Comment by ADRIYAN529** [comment]
No milestone

**Comment by ADRIYAN529** [comment]
syahadriyan529@gmail.com

**Comment by ADRIYAN529** [comment]
Manta

**Comment by ADRIYAN529** [comment]
Project

**Comment by ADRIYAN529** [comment]
Patch

**Comment by ADRIYAN529** [comment]
Diff

**Pull request merged**
