### PR TITLE
update: update op-node to celestia-3.0.0-dencun

### PR DESCRIPTION
**Pull request by wangchengao**
During data synchronization,  public.ecr.aws/i6b2w2n6/op-node:celestia-3.0.0  encounters an error: "transaction type not supported" .
So upgrade public.ecr.aws/i6b2w2n6/op-node:celestia-3.1.0 to solve this issue.

### CODE REVIEW

**Comment by wangchengao** [comment]
@jincan39 @DanielZhangReal

**Comment by wangchengao** [comment]
@anaye1997 plz help merge.

**Comment by lcrypton** [comment]
It seems that there is a new version `public.ecr.aws/i6b2w2n6/op-node:4.0.0` . You can check it [here](https://gallery.ecr.aws/i6b2w2n6/op-node)

**Review by anaye1997 — CHANGES_REQUESTED** [review]

**Comment by wangchengao** [comment]
@anaye1997 has commited the change.

**Review by anaye1997 — APPROVED** [review]

**Comment by anaye1997** [comment]
> @anaye1997 has commited the change.

thanks for this change @wangchengao seems your first commit is not signed with gpg (we have a merge policy all commit to be signed by user's gpg key)

image

**Comment by anaye1997** [comment]
thanks for the PR @wangchengao, we've included the change in https://github.com/Manta-Network/docs/pull/262, closing this one

**Comment by wangchengao** [comment]
ok, thanks.

**Pull request closed without merging**
