### PR TITLE
Adding Cookbook.dev's AI Web3 Technical Documentation Bot & Tutorial on Deploying to Manta Pacific using Cookbook.dev 

### PR DESCRIPTION
**Pull request by MikeDank**
**What changed? Why?**
This pull request completes the integration for the addition of Cookbook.dev's AI Web3 assistant that appears as a button and pop-up in the Manta Network technical documentation. Enhanced Q&A and technical documentation search, along with the ability for users to highlight portions of the docs and have them explained. Details for this integration have been discussed with Manta Network team members. 

This pull request also introduces a new section of documentation detailing additional ways developers can quickly deploy smart contracts to Manta Pacific Cookbook.dev. The changes are based on the existing structure and format of the Manta-Network/docs repository. The primary goal of this addition is to enhance the ease at which developers can access smart contract research, development and deployment for Base.

**Notes to reviewers**
Followed all documentation contribution guidelines and looking forward to any feedback or any questions. 

**How has it been tested?**
Local Testing: The documentation section has been tested locally to ensure all markdown files render correctly and the navigation between sections is smooth and intuitive.
Staging Deployment: A version of this update has been deployed to our staging environment using Vercel. This allowed us to view the documentation in a web format, ensuring that it displays correctly in a real-world setting.

We conduct ongoing extensive testing on our AI Web3 assistant to ensure accurate answers.

### CODE REVIEW

**Comment by zoulihong1018** [comment]
issue1,The icon in the top left corner is not displayed
image

issue2, select content, then click Explain, ChefGPT ICONS overlap
image

**Comment by jincan39** [comment]
@ClockRide @TylerSehr Appreciated for the work, overall the code looks good to me. But it would be more great if you can resolve the explain button's background style issue, remove useless code and fix some type issue before commits(For some unnecessary rules, [just turn off rules here](https://github.com/Manta-Network/docs/commit/fc80ae528c553a232dc73f3ae5fc7b7cdef07162#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5R32)). 
This requires a squash commit and rebase onto Manta-Network/docs/tree/staging, and you can check the details locally.
- step 1 : this PR will squash to branch feat/cookbook
- step 2: pull & checkout feat/cookbook, then git reset --soft fc80ae5
- step 3: git commit -m 'feat: cookbook xxx' and the lint result will be in the console

**Review by jincan39 — DISMISSED** [review]

**Comment by jincan39** [comment]
@TylerSehr Thanks, clean approach. Please rebase onto Manta-Network/docs/tree/main and solve the conflict.

**Review by jincan39 — APPROVED** [review]

**Review by jincan39 — DISMISSED** [review]
LGTM

**Comment by jincan39** [comment]
image

the devops side need commits to be signed, please squash to one signed commit like this https://github.com/Manta-Network/docs/pull/241. cc @TylerSehr

**Comment by ClockRide** [comment]
> image
> the devops side need commits to be signed, please squash to one signed commit like this #241. cc @TylerSehr

Squashed all changes into one signed commit :)
Feel free to tag me if we need to make any other changes

**Comment by ClockRide** [comment]
> @ClockRide Nice job, there should be 4 files changed, not 24 files. Please recheck image

Sorry, I included a bunch of new changes from the manta-network repo in my commit. I've cleaned it up now and included an article authored by @MikeDank about cookbook.dev, which we would like to add to the deployment section of the documentation. Let me know once you've had a chance to review if we're good to go. Thanks!

**Review by jincan39 — APPROVED** [review]

**Comment by jincan39** [comment]
@ClockRide Appreciated, Nice work!

**Pull request merged**
